### PR TITLE
Add sizeof() method

### PR DESCRIPTION
**Pull request by YuliyaCl**
Related to https://github.com/JuliaPackaging/RelocatableFolders.jl/issues/25

### CODE REVIEW

**Comment by MichaelHatherly** [comment]
CI failures will be fixed with https://github.com/JuliaPackaging/RelocatableFolders.jl/pull/27.

**Comment by MichaelHatherly** [comment]
Thanks, can you add a test that reproduces #26, probably by adding `JSON3` as a test-only dependency and trying to read a `Path` with it?

**Comment by YuliyaCl** [comment]
Sure.
I've find an another error.. working on it yet.

**Comment by MichaelHatherly** [comment]
That ones merged so you should be able to rebase and CI will likely run fine.

**Comment by sairus7** [comment]
Still not working:

```julia

import Pkg
Pkg.activate(; temp=true)
Pkg.add("JSON3")
# Pkg.develop("RelocatableFolders")
Pkg.add(url="https://github.com/YuliyaCl/RelocatableFolders.jl", rev="dev")
using JSON3

open("test.json", "w") do io
    write(io, """
    {
        "cmd":"change_qrs_group",
        "tbeg":280,
        "tend":310,
        "polymorph":false,
        "form_src":["S"],
        "form_dst":"V",
        "target":"qrs_L1"
    }
    """)
end

module TestJSON
    using JSON3, RelocatableFolders 
    const FP = @path raw"test.json"
    readfile() = JSON3.read(FP, Dict{String, Any})

end

using .TestJSON
TestJSON.readfile() # ok
rm(raw"test.json")
TestJSON.readfile() # error
```

**Comment by MichaelHatherly** [comment]
What happens if it's an entire relocatable folder rather than a single file?

**Comment by sairus7** [comment]
The same happens with 
```julia
const FP = @path joinpath(@__DIR__, "test.json")
````
Maybe this is Windows-specific?

**Comment by MichaelHatherly** [comment]
> Maybe this is Windows-specific?

It's the specific behaviour of how the lookup works for single files compared to folders.

```julia
import Pkg
Pkg.activate(; temp=true)
Pkg.add("JSON3")
# Pkg.develop("RelocatableFolders")
Pkg.add(url="https://github.com/YuliyaCl/RelocatableFolders.jl", rev="dev")
using JSON3

mkdir("subfolder")
open("subfolder/test.json", "w") do io
    write(io, """
    {
        "some":"data"
    }
    """)
end

module TestJSON
    using JSON3, RelocatableFolders 
    const FP = @path "subfolder"
    readfile() = JSON3.read(joinpath(FP, "test.json"), Dict{String, Any})

end

using .TestJSON
TestJSON.readfile() # ok
rm("subfolder"; recursive = true)
TestJSON.readfile() # error

julia> using .TestJSON

julia> TestJSON.readfile() # ok
Dict{String, Any} with 1 entry:
  "some" => "data"

julia> rm("subfolder"; recursive = true)

julia> TestJSON.readfile() # error
Dict{String, Any} with 1 entry:
  "some" => "data"

julia> String(TestJSON.FP)
"/Users/mike/.julia/scratchspaces/00000000-0000-0000-0000-000000000000/eb780816b1b3b97466ed0960cdccc63143468b80_35OXSZ67gRZ"

julia> mkdir("subfolder")
"subfolder"

julia> String(TestJSON.FP)
"/Users/mike/pumas/PumasCP.jl/subfolder"

julia> TestJSON.readfile() # error
ERROR: ArgumentError: invalid JSON at byte position 1 while parsing type JSON3.Object: ExpectedOpeningObjectChar
/Users/mike/pumas/PumasCP.

Stacktrace:
 [1] invalid(error::JSON3.Error, buf::Base.CodeUnits{UInt8, String}, pos::Int64, T::Type)
   @ JSON3 ~/.julia/packages/JSON3/L8Yfy/src/JSON3.jl:30
 [2] #read#43
   @ ~/.julia/packages/JSON3/L8Yfy/src/structs.jl:429 [inlined]
 [3] read
   @ ~/.julia/packages/JSON3/L8Yfy/src/structs.jl:353 [inlined]
 [4] #read#42
   @ ~/.julia/packages/JSON3/L8Yfy/src/structs.jl:351 [inlined]
 [5] read
   @ ~/.julia/packages/JSON3/L8Yfy/src/structs.jl:351 [inlined]
 [6] read(str::String, ::Type{Dict{String, Any}}; jsonlines::Bool, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ JSON3 ~/.julia/packages/JSON3/L8Yfy/src/structs.jl:41
 [7] read
   @ ~/.julia/packages/JSON3/L8Yfy/src/structs.jl:33 [inlined]
 [8] readfile()
   @ Main.TestJSON ./REPL[29]:4
 [9] top-level scope
   @ REPL[37]:1

julia>
```

Basically it's a separate issue unrelated to JSON3 in the reported issue. Let's keep that for a separate issue/PR rather than trying to resolve it here as well.

**Comment by MichaelHatherly** [comment]
I see there's some additional invalidations happening now. @YuliyaCl are you happy to try take a look at resolving those? If not then I can take a look myself, but it's going to have to wait a while until I have the spare time.

**Comment by YuliyaCl** [comment]
@MichaelHatherly I'm not sure that I may resolve them correctly... So It'll be much better if you have opportunity to look through later.

**Comment by sairus7** [comment]
Yes, here is a simpler example not involving JSON3. Looks like it works with entire folder but not with a single file
```julia
import Pkg
Pkg.activate(; temp=true)
# Pkg.add("RelocatableFolders")
Pkg.add(url="https://github.com/YuliyaCl/RelocatableFolders.jl", rev="dev")

open("test1.txt", "w") do io
    write(io, "some data")
end

mkdir("subfolder")
open("subfolder/test2.txt", "w") do io
    write(io, "another data")
end

module MyTest
    using RelocatableFolders 
    const FILE = @path joinpath(@__DIR__, "test1.txt")
    const FOLDER = @path joinpath(@__DIR__, "subfolder")
    read_from_file() = read(FILE, String)
    read_from_folder() = read(joinpath(FOLDER, "test2.txt"), String)
end

using .MyTest
MyTest.read_from_file() # ok
MyTest.read_from_folder() # ok

rm("subfolder"; recursive = true)
MyTest.read_from_folder() # ok

rm("test1.txt")
MyTest.read_from_file() # error

```

**Comment by MichaelHatherly** [comment]
@sairus7 please open a separate issue for that, thanks.

**Comment by sairus7** [comment]
Made a separate issue: https://github.com/JuliaPackaging/RelocatableFolders.jl/issues/28

**Comment by MichaelHatherly** [comment]
Replaced by #30, thank you for reporting the issue @YuliyaCl. Let me know if the next release containing that fix doesn't address the issue for you. I'll be tagging a new patch release shortly.

**Pull request closed without merging**
